# Generated by Django 4.2.4 on 2023-08-31 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('email', models.EmailField(max_length=300, verbose_name='email')),
                ('fullname', models.CharField(max_length=300, verbose_name='email')),
                ('message', models.TextField(verbose_name='Contact Us')),
                ('is_read_by_admin', models.BooleanField(verbose_name='')),
                ('created_date', models.TimeField(default=datetime.datetime, editable=False)),
                ('response', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
