# Generated by Django 4.2.4 on 2023-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_alter_contact_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
