# Generated by Django 4.2.4 on 2023-09-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0009_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
