# Generated by Django 4.2.4 on 2023-09-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0010_profile_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_user',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
